### ISSUE TITLE
Add properties for orderedKeys and orderedValues

### ISSUE THREAD

**Issue by lukaskubanek** [lukaskubanek/OrderedDictionary#1]

**Comment by balazsgerlei** [comment]
What happened with this issue? Is it possible to retreive an array of ordered keys and ordered values now?

**Comment by lukaskubanek** [comment]
Hi @balazsgerlei. Yes, it's possible. There are two properties `orderedKeys` & `orderedValues` which return lazy collections of keys & values wrapped into lazy collection types. They have the benefit that when accessed no new memory has to be allocated. In order to convert them to arrays, use `Array(orderedDictionary.orderedKeys)` & `Array(orderedDictionary.orderedValues)`.
