### ISSUE TITLE
Safe for app extensions

### ISSUE THREAD

**Issue by graphiclife** [lukaskubanek/OrderedDictionary#10]
When linking the framework for an extension there's a warning saying the framework is not safe for use in app extensions. Fixable?

**Comment by lukaskubanek** [comment]
Hi, thanks for reporting this issue. Unfortunately I have no experience with extensions development. Maybe you could help me with this issue by:
1. Providing the exact warning message.
2. Googling the cause of this issue and figuring out a way to remove the warning. It is also necessary to know whether it has to be done in the framework or in the extension target which embeds it.
3. Possibly creating a simple project which displays that warning and uploading it somewhere.

**Comment by graphiclife** [comment]
Should be as easy as setting the "Require Only App-Extension-Safe API" to Yes.

![app-extension](https://cloud.githubusercontent.com/assets/217371/14461295/2a2db99e-00c2-11e6-9138-dafec9f0c25a.png)

**Comment by lukaskubanek** [comment]
I've changed the settings, could you please test it against `master`? If the warning disappears, I'd release a new version.

**Comment by lukaskubanek** [comment]
The change is included in the [version 0.7](https://github.com/lukaskubanek/OrderedDictionary/releases/tag/v0.7)

**Comment by graphiclife** [comment]
@lukaskubanek It seems this is an issue again in the newest release :)

**Comment by lukaskubanek** [comment]
Which release are you referring to? `v2.1.0` or `master`? What Xcode and Swift versions are you using?

**Comment by graphiclife** [comment]
Both 2.1.0 and master. I’m compiling with Xcode 10.2 and Swift 4.2.
