### ISSUE TITLE
How to set value?

### ISSUE THREAD

**Issue by dzpt** [lukaskubanek/OrderedDictionary#16]
I want to fill up value from json data but it didn't work

```
// json data
let abc:[String:AnyObject] = ["A": [1], "B": [2], "C": [3], "D": [4]]
var od: OrderedDictionary<String, AnyObject> = abc
```

> error: cannot convert value of type '[String : AnyObject]' to specified type 'OrderedDictionary<String, AnyObject>'
> var od: OrderedDictionary<String, AnyObject> = abc

I've tried

`var od: OrderedDictionary<String, AnyObject> = abc as! OrderedDictionary<String, AnyObject>`

But didn't work also

**Comment by lukaskubanek** [comment]
You can assign the dictionary literal directly to the variable of type `OrderedDictionary<String, AnyObject>` like this:

``` swift
let orderedDictionary: OrderedDictionary<String, AnyObject> = ["A": [1], "B": [2]]
```

However if the dictionary is dynamically constructed, there is no direct way to convert it to the ordered dictionary. In that case I'd suggest to map the dictionary to an array of key-value tuples and use it to initialize the ordered dictionary. Be aware of the non-deterministic ordering of the dynamic data in pure `Dictionary`. You better sort those elements according your specific logic before constructing the ordered dictionary.

``` swift
let dictionary: [String: AnyObject] = ["A": [1], "B": [2]]
let elements = dictionary.map({ ($0, $1) })
let sortedElemetns = elements.sort(...)
let orderedDictionary = OrderedDictionary<String: AnyObject>(elements: sortedElements)
```

I hope this helps. If you have further questions, feel free to ask.
