### ISSUE TITLE
A swift3 branch is welcome

### ISSUE THREAD

**Issue by tcalin** [lukaskubanek/OrderedDictionary#17]
```
public func index(after i: OrderedDictionary.Index) -> OrderedDictionary.Index {
    return (i + 1)
  }
```

This is all was needed to make it compile (to satisfy protocol changes). Still there are some warnings.

**Comment by lukaskubanek** [comment]
I hope to start with the migration to Swift 2.3/3 during the next week.

**Comment by jdordoigne** [comment]
Any update?

**Comment by lukaskubanek** [comment]
Due to those frequent changes in the development process of Swift 3 I decided to wait until the final release. In the next weeks I'm going to tackle the update of my app to Swift 3 and since my uses this library I am going to update it as well.

**Comment by jdordoigne** [comment]
The final release is out since tuesday :) https://swift.org/blog/

**Comment by lukaskubanek** [comment]
I know 😉

**Comment by lukaskubanek** [comment]
Currently I'm waiting for ReactiveCocoa to get updated for Swift 3, so that I can start updating my app and in turn this library. For now I've created [a release](https://github.com/lukaskubanek/OrderedDictionary/releases/tag/v0.8) which targets Swift 2.3.

**Comment by callo90** [comment]
any update? why do you need ReactiveCocoa?

**Comment by lukaskubanek** [comment]
@tcalin @jdordoigne There is now a Swift 3 branch and the development is tracked in #23. Expect a new release in the coming days.
