### ISSUE TITLE
store orderedDictionary in DataBase error

### ISSUE THREAD

**Issue by haneen91** [lukaskubanek/OrderedDictionary#27]
I need to store the ordered dictionary into database I tried to convert it to BLOB but there is error ,I used NSKeyedArchiever to convert NSDicitonary to Blob

**Comment by lukaskubanek** [comment]
Hi, OrderedDictionary does not support serialization via `NSKeyedArchiver` since it is not a subclass of `NSObject` but rather a Swift struct. Conversion to `NSDictionary` would not help you either, since the order would be lost. You have to implement your own serialization logic in this case.
