### ISSUE TITLE
Need sample code 

### ISSUE THREAD

**Issue by balakrishnaJarugubelli** [lukaskubanek/OrderedDictionary#29]
Hi,

Could you please provide sample code and documentation??

I have a unsorted dictionary. how can I use your library to make it as orderdDict

It's bit tricky with init methods(Elements/Sequences). Please suggest as I am new to Swift.

Thanks in advance.

**Comment by lukaskubanek** [comment]
Hi, you can find sample code [in the playground included in the repository](https://github.com/lukaskubanek/OrderedDictionary/blob/master/Playgrounds/OrderedDictionary.playground/Contents.swift). For API documentation please refer to the comments [in the source files](https://github.com/lukaskubanek/OrderedDictionary/blob/master/Sources/OrderedDictionary.swift). I will eventually turn the code comments into an API documentation using Jazzy in #24.

Regarding your specific problem, there is actually not a simple way for doing it. I might add a secondary initializer which would take a dictionary and a sort function in the future (see #30). For now you have to construct the elements sequence from the dictionary on your own and apply custom sorting. Here is an example:

```swift
let dictionary = [
    1: "foo",
    2: "bar",
    3: "baz"
]

let unsortedElements = dictionary .map { key, value in
    return (key: key, value: value)
}

let sortedElements = unsortedElements.sorted { element1, element2 in
    return element1.key < element2.key
}

let orderedDictionary = OrderedDictionary<Int, String>(sortedElements)
```
