### ISSUE TITLE
Add methods for popping and removal

### ISSUE THREAD

**Issue by lukaskubanek** [lukaskubanek/OrderedDictionary#33]
- `popFirst()`
- `removeFirst()`
- `popLast()`
- `removeLast()`

**Comment by lukaskubanek** [comment]
For implementation see @maicki's fork: https://github.com/maicki/OrderedDictionary/commit/d73a3f979439993b3f03f6e461e72bfce4103c67

**Comment by maicki** [comment]
I created branch for it, PR will follow in a bit: https://github.com/maicki/OrderedDictionary/tree/maicki/popping-removal
