### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by igordeoliveirasa** [lukaskubanek/OrderedDictionary#35]
What about CocoaPods?

**Comment by lukaskubanek** [comment]
Hi Igor, see #7 and #26 for the answer.

**Comment by shayneoneill** [comment]
You should really reconsider this. Regardless of what the final fate of Cocoapods is, its by a *massive* margin the defacto standard, and its a royal pain in the neck having to constantly diff this library for changes against a locally copied version

**Comment by lukaskubanek** [comment]
You don’t have to maintain a local copy of this library. All you have to do is to maintain a custom podspec for the library which is pointing to this repository. You can even publish that podspec and share it with others. I’m not using Cocoapods and it would be a huge pain to setup an environment and test it inside after each release.
