### ISSUE TITLE
Archive issue

### ISSUE THREAD

**Issue by callo90** [lukaskubanek/OrderedDictionary#36]
Hey guys,

Im getting this error after archiving and submitted a new version using xcode 9
<img width="623" alt="screen shot 2017-09-20 at 1 09 54 am" src="https://user-images.githubusercontent.com/808411/30629269-8de15f32-9da0-11e7-811b-5c3c3569fa6b.png">

Framework plist
<img width="912" alt="screen shot 2017-09-20 at 1 11 38 am" src="https://user-images.githubusercontent.com/808411/30629285-ae85b35a-9da0-11e7-80ca-0c95e719f9ed.png">

You might need your current version format and use only numbers instead

**Comment by lukaskubanek** [comment]
Hi @callo90, this is most likely the case. I didn't know that you have to use only three numeric components for the version in Info.plist. The solution would be to remove the beta suffix from the version identifier which I will do in the next beta version. As a workaround for now you might remove it manually. Please let me know if it worked for you.

**Comment by callo90** [comment]
Working fine dude...thanks

**Comment by callo90** [comment]
There's another issue which is affecting you guys, please see

https://github.com/Carthage/Carthage/issues/2056

**Comment by callo90** [comment]
codeCoverageEnabled should be set as false, apple is invalidating builds

```Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.```

**Comment by lukaskubanek** [comment]
Both issues were fixed by your pull request #37. Thanks for your contribution. A new version follows in a few minutes.
