### ISSUE TITLE
Task failed with exit code 65 in Swift4 Xcode 9

### ISSUE THREAD

**Issue by JackySONE** [lukaskubanek/OrderedDictionary#38]
hi, I want to use xcode9 (Swift 4) for new project, but I can't use carthage to build a framework

this the build failed message:
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

**Comment by lukaskubanek** [comment]
Is this maybe related to #36? Does it still happen with the just released [version 1.0.0](https://github.com/lukaskubanek/OrderedDictionary/releases/tag/v1.0.0)?

**Comment by JackySONE** [comment]
It's fine, now. Run carthage bootstrap could build the framework successfully.

**Comment by lukaskubanek** [comment]
Glad to hear that.
