### ISSUE TITLE
Add method for converting a Dictionary to OrderedDictionary

### ISSUE THREAD

**Issue by lukaskubanek** [lukaskubanek/OrderedDictionary#39]
```Dictionary.sorted(by areInIncreasingOrder: (Element, Element) -> Bool) -> OrderedDictionary<Key, Value>```

**Comment by lukaskubanek** [comment]
For implementation see @maicki's fork: https://github.com/maicki/OrderedDictionary/commit/37ace5f3873122dc5155c2dacd50b813be5001b5

**Comment by maicki** [comment]
I created branch for it, PR will follow in a bit: https://github.com/maicki/OrderedDictionary/tree/maicki/dictionary-to-ordereddictionary

**Comment by lukaskubanek** [comment]
Thanks, no need to create a PR, I'm going to add it now.
