### ISSUE TITLE
Swift package manager

### ISSUE THREAD

**Issue by jnordberg** [lukaskubanek/OrderedDictionary#42]
Would be great if OrderedDictionary was compatible with SPM

Big thanks for this lib btw, I've used it in several projects

**Comment by lukaskubanek** [comment]
> Would be great if OrderedDictionary was compatible with SPM

Definitely! But since Xcode does not support it yet and I don't work on server side code, I don't have any experience with that setup. So unless someone from the community helps out I leave this issue open and possibly add the support later.

> Big thanks for this lib btw, I've used it in several projects

Glad to hear that. 👍
