### ISSUE TITLE
Key based access fails with error when Dictionary key is an integer type

### ISSUE THREAD

**Issue by danielvy** [lukaskubanek/OrderedDictionary#49]
Consider the following:

```
let dict: OrderedDictionary<UInt, String> = [1: "1", 2: "2", 3: "3"]
let x = dict[4]
```

The compiler will not complain and this will throw an error by the precondition in the index based subscript.

The expected behavior is like base Dictionary, returning nil when the key doesn't exists. 

This happens because in this case, the requested key (4) is assumed to be an `Int` and therefore the index subscript gets called instead of the key subscript.

In the following case:

```
let dict: OrderedDictionary<Int, String> = [1: "1", 2: "2", 3: "3"]
let x = dict[4]
```

The compiler will complain about _ambiguous use of 'subscript'_ . It can be resolved by explicitly casting the result to value's type but makes the `OrderedDictionary` less usable.

I think the solution here is to wrap the index with a specific index type to resolve any possible ambiguity between the index and key. Which is what the foundation's Dictionary does.

**Comment by lukaskubanek** [comment]
> The compiler will not complain and this will throw an error by the precondition in the index based subscript. The expected behavior is like base Dictionary, returning nil when the key doesn't exists.

As you write, this happens because the index subscript is chosen and it behaves the same as `Array` from the STL when asked for a missing index.

> The compiler will complain about ambiguous use of 'subscript' . It can be resolved by explicitly casting the result to value's type but makes the OrderedDictionary less usable.

This is in fact a problem. Instead of casting, you can always reach for the `value(forKey:)` method instead of a subscript.

> I think the solution here is to wrap the index with a specific index type to resolve any possible ambiguity between the index and key. Which is what the foundation's Dictionary does.

I don't think this approach would solve the problem with ambiguous subscripts. You would still want to access the key-value pair at a specific index using an integer literal and there would still be an ambiguity. A better solution would be have two named subscripts: `dict[index: 4]` and `dict[key: 4]`. What do you think?

**Comment by danielvy** [comment]
> I don't think this approach would solve the problem with ambiguous subscripts. You would still want to access the key-value pair at a specific index using an integer literal and there would still be an ambiguity.

Why doesn't this solve the problem? 

The foundation Dictionary uses a special struct for its indices, which can't be used accidentally as the Dictionary's key.

You can do that as well, something like this:

```
public typealias Index = OrderedDictionaryIndex

public struct OrderedDictionaryIndex : Comparable {
  let index: Array<Key>.Index
  
  public static func < (lhs: OrderedDictionaryIndex, rhs: OrderedDictionaryIndex) -> Bool {
    return lhs.index < rhs.index
  }
}
  
public var startIndex: Index {
  return OrderedDictionaryIndex(index: _orderedKeys.startIndex)
}

public var endIndex: Index {
  return OrderedDictionaryIndex(index: _orderedKeys.endIndex)
}

public func index(after i: Index) -> Index {
  return OrderedDictionaryIndex(index: _orderedKeys.index(after: i.index))	
}

public subscript(position: Index) -> Element {
  precondition(indices.contains(position.index), "OrderedDictionary index is out of range")
  
  let key = _orderedKeys[position.index]
  let value = _unsafeValue(forKey: key)
  
  return (key, value)
}
```

Using the `OrderedDictionaryIndex` as index will prevent accessing the index subscript by mistake or any ambiguity (unless deliberately using this type as key) while satisfying the `Collection` protocol. You can access the key subscript as is, if you need to access an element by index (which you almost never need in a Dictionary), you can do: `dict[OrderedDictionaryIndex(index:` 1)]

Won't this solve the problem?

**Comment by lukaskubanek** [comment]
> if you need to access an element by index (which you almost never need in a Dictionary)

You certainly don't in a `Dictionary` but the point of the `OrderedDictionary` structure is actually to be able to do it...

> `dict[OrderedDictionaryIndex(index: 1)]`

Of course it would be possible to do it this way but I don't like this API at all. In my last comment, I was referring to such a type which would conform to `ExpressibleByIntegerLiteral` to have a sane subscript syntax and to be able to still access a key-value pair using an integer literal.

From my point of view, having two named subscripts is still a better solution. At the time of the initial implementation, this feature was not supported by Swift.

**Comment by danielvy** [comment]
You can't conform to `Collection` protocol with just named subscripts. You must have a default subscript that can access elements by index. So your `OrderCollection` will always have at least one unnamed subscript with index access.

Because it's a **Dictionary**, anyone using it expects to access its values by key by default. So you need to implement a default subscript to access it by key.

In any case where the type of the Index is ambiguous with the type of the Key, you will have the problem mentioned above. You can't solve it this way unless you forego the default key access subscript. Which would be a mistake, imho, because this is not what users expect from a Dictionary.

What you can do is implement the solution I suggested above and add just one named subscript:

```
public subscript(index index: Int) -> Element {
  get {
    return self[OrderedDictionaryIndex(index: index)]
  }
}
```

That way you can access the value by key, as expected:
`let x = dict[1] // Will return the value for key 1 and nil if not present`

And access the index with named subscript:
`let x = dict[index: 1] // Will return the value at index 1, and throw error if out of bounds`

All `Collection` methods will continue to work with the default Index subscript (and the `OrderedDictionaryIndex` wrapper)  transparently.

**Comment by lukaskubanek** [comment]
True, I forgot that the index subscript method is required by the `Collection` protocol. In this case, your recent suggestion would fit perfectly and having one additional named subscript would do the job. Thanks for your idea! I will consider implementing it in the next version.

**Comment by lukaskubanek** [comment]
@danielvy: As part of a bigger overhaul of `OrderedDictionary`, I looked into this issue. Your initially proposed approach worked well for resolving the issue of subscript ambiguity when using `Int` as the key type by giving the key precedence over the index.

After implementing this (see attached patch below) and checking against my codebase, I realized the downside of this approach, which is the need for wrapping indices to the `Index` type at every other spot of the public API.

This newly created inconvenience is even worse than the special case of using `Int` as the key type. For this reason, I’m going to stick with `Int` as the index type, and I’m suggesting you use one of the following issues to deal with the ambiguity:

- Using a key type other than `Int` in your instance
- Using methods instead of subscripts
- Explicitly casting the return types when calling to subscripts

By the way, the current progress of the work on v4.0 can be looked up in #69. I’ve included tests for resolving the ambiguity using explicit return types as well.

---

```patch
diff --git a/Sources/OrderedDictionary.swift b/Sources/OrderedDictionary.swift
index 2acb630..1d83305 100644
--- a/Sources/OrderedDictionary.swift
+++ b/Sources/OrderedDictionary.swift
@@ -8,11 +8,8 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
     /// The type of the key-value pair stored in the ordered dictionary.
     public typealias Element = (key: Key, value: Value)
     
-    /// The type of the index.
-    public typealias Index = Int
-    
     /// The type of the indices collection.
-    public typealias Indices = CountableRange<Int>
+    public typealias Indices = CountableRange<Index>
     
     /// The type of the contiguous subrange of the ordered dictionary's elements.
     public typealias SubSequence = Slice<Self>
@@ -141,30 +138,25 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
     
-    /// The indices that are valid for subscripting the ordered dictionary.
-    public var indices: Indices {
-        return _orderedKeys.indices
-    }
-    
     /// The position of the first key-value pair in a non-empty ordered dictionary.
     public var startIndex: Index {
-        return _orderedKeys.startIndex
+        return Index(_orderedKeys.startIndex)
     }
     
     /// The position which is one greater than the position of the last valid key-value pair
     /// in the ordered dictionary.
     public var endIndex: Index {
-        return _orderedKeys.endIndex
+        return Index(_orderedKeys.endIndex)
     }
     
     /// Returns the position immediately after the given index.
     public func index(after i: Index) -> Index {
-        return _orderedKeys.index(after: i)
+        return Index(_orderedKeys.index(after: i.value))
     }
     
     /// Returns the position immediately before the given index.
     public func index(before i: Index) -> Index {
-        return _orderedKeys.index(before: i)
+        return Index(_orderedKeys.index(before: i.value))
     }
     
     /// Returns the index for the given key.
@@ -174,7 +166,9 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
     /// - Returns: The index for `key` and its associated value if `key` is in the ordered
     ///   dictionary; otherwise, `nil`.
     public func index(forKey key: Key) -> Index? {
-        return _orderedKeys.firstIndex(of: key)
+        return _orderedKeys
+            .firstIndex(of: key)
+            .flatMap(Index.init(_:))
     }
@@ -273,7 +267,7 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
         
         let currentValue = self[index].value
         
-        _orderedKeys.remove(at: index)
+        _orderedKeys.remove(at: index.value)
         _keysToValues[key] = nil
         
         return currentValue
@@ -318,7 +312,7 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
                 "OrderedDictionary index is out of range"
             )
             
-            let key = _orderedKeys[position]
+            let key = _orderedKeys[position.value]
             let value = _unsafeValue(forKey: key)
             
             return (key, value)
@@ -388,7 +382,7 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
         
         let (key, value) = newElement
         
-        _orderedKeys.insert(key, at: index)
+        _orderedKeys.insert(key, at: index.value)
         _keysToValues[key] = value
     }
     
@@ -443,7 +437,7 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
         }
         
         // Store the new position of the key and the new value associated with the key.
-        _orderedKeys[index] = key
+        _orderedKeys[index.value] = key
         _keysToValues[key] = value
         
         return replacedElement
@@ -461,7 +455,7 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
     public mutating func remove(at index: Index) -> Element? {
         guard let element = elementAt(index) else { return nil }
         
-        _orderedKeys.remove(at: index)
+        _orderedKeys.remove(at: index.value)
         _keysToValues.removeValue(forKey: element.key)
         
         return element
@@ -523,7 +517,7 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
     /// - Precondition: Both indices must be valid existing indices of the ordered dictionary.
     /// - Complexity: O(1)
     public mutating func swapAt(_ i: Index, _ j: Index) {
-        _orderedKeys.swapAt(i, j)
+        _orderedKeys.swapAt(i.value, j.value)
     }

@@ -650,6 +644,62 @@ public struct OrderedDictionary<Key: Hashable, Value>: RandomAccessCollection, M
     
 }
+
+extension OrderedDictionary {
+    
+    /// The position of a key-value pair in an ordered dictionary.
+    public struct Index: Hashable {
+        
+        public init(_ value: Int) {
+            self.value = value
+        }
+        
+        /// The position value.
+        public let value: Int
+        
+    }
+    
+}
+
+extension OrderedDictionary.Index: Comparable {
+    
+    public static func < (lhs: Self, rhs: Self) -> Bool {
+        return lhs.value < rhs.value
+    }
+    
+}
+
+extension OrderedDictionary.Index: Strideable {
+    
+    public func distance(to other: Self) -> Int {
+        return value.distance(to: other.value)
+    }
+    
+    public func advanced(by n: Int) -> Self {
+        return Self(value.advanced(by: n))
+    }
+    
+}
+
+extension OrderedDictionary.Index: CustomStringConvertible {
+    
+    public var description: String {
+        return value.description
+    }
+    
+}
+
+extension OrderedDictionary.Index: ExpressibleByIntegerLiteral {
+    
+    public init(integerLiteral value: Int) {
+        self.init(value)
+    }
+    
+}
+
```
