### ISSUE TITLE
Package.swift seems invalid for Swift 4.2.1

### ISSUE THREAD

**Issue by Fryie** [lukaskubanek/OrderedDictionary#51]
After [this commit](https://github.com/lukaskubanek/OrderedDictionary/commit/77d0b4937a1f60737dddd868f7f242fad91a8b7c), I cannot build the repository with `swift build` and Swift 4.2.1.

The issue seems to be a breaking change between the PackageDescription APIs [4](https://github.com/apple/swift-package-manager/blob/b73299ef84e1e55c789052d0d1eafec30a95a805/Documentation/PackageDescriptionV4.md) and [4.2](https://github.com/apple/swift-package-manager/blob/b73299ef84e1e55c789052d0d1eafec30a95a805/Documentation/PackageDescriptionV4_2.md).

I'm not sure if changing the first line to say `// swift-tools-version: 4` would help, maybe then the old format would be selected.

**Comment by lukaskubanek** [comment]
I've attempted to fix this issue in [v2.2.1](https://github.com/lukaskubanek/OrderedDictionary/releases/tag/v2.2.1). Could you please give it a try?

**Comment by Fryie** [comment]
@lukaskubanek works, thank you!
