### ISSUE TITLE
OrderedDictionary does not serialize to JSON using JSONSerialization or JSONEncoder

### ISSUE THREAD

**Issue by codecat15** [lukaskubanek/OrderedDictionary#53]
This is not a bug but moreover, a feature request.

what I would like to see is the dictionary getting converted to JSON using the native JSONSerialization class or JSONEncoder if you can add support for that it will be really awesome.

I tried to use the OrderedDictionary and tried to convert it to JSON using the below code

    
    let serializedData = try! JSONSerialization.data(withJSONObject: orderedDictionaryObj, options: [])
        let encodedData = String(data: serializedData, encoding: String.Encoding.utf8)

but for now if you try to do something like this the JSONSerialization throws an exception. It will be really nice if you can add an extension method or expose a property to do this like

`orderedDictionaryObject.ToJSONString()`

Really appreciate the work and thanks for sharing this

**Comment by lukaskubanek** [comment]
@codecat15: `OrderedDictionary` is not an object and thus cannot be used with `JSONSerialization` API. There is a new API based on [`Codable`](https://www.swiftbysundell.com/basics/codable) which is fully supported by `OrderedDictionary`. Look into [`JSONEncoder`](https://developer.apple.com/documentation/foundation/jsonencoder) & [`JSONDecoder`](https://developer.apple.com/documentation/foundation/jsondecoder).
