### ISSUE TITLE
Error -  Type 'OrderedDictionary<Key, Value>' does not conform to protocol 'CollectionType'

### ISSUE THREAD

**Issue by rlaferla** [lukaskubanek/OrderedDictionary#6]
Using XCode 7.1.1:

ERROR

Type 'OrderedDictionary<Key, Value>' does not conform to protocol 'CollectionType'

**Comment by lukaskubanek** [comment]
Which version of OrderedDictionary are you using?

**Comment by lukaskubanek** [comment]
Closed because of no response.
