### ISSUE TITLE
V3.0.0 CFBundleShortVersionString missing

### ISSUE THREAD

**Issue by PolitieRool** [lukaskubanek/OrderedDictionary#62]
I've updated the framework to v.3.0.0 with Carthage, and I'm getting an error while submitting to the appStore: 
`parameter ErrorMessage = ERROR ITMS-90057: "The bundle 'Payload/PolitieApp.app/Frameworks/OrderedDictionary.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring`

**Comment by lukaskubanek** [comment]
@PolitieRool: Thanks for reporting! I didn’t know that this entry is required in the Info.plist. Anyway, I just released version 3.0.1. Can you please try to submit it again and let me know here whether it works?

**Comment by PolitieRool** [comment]
@lukaskubanek Thanks for this speedy fix! I can confirm that v3.0.1 does fix this and I was able to upload my build to the appStore for deployment. Thanks!

**Comment by lukaskubanek** [comment]
@PolitieRool: Thanks for letting me know!
