### ISSUE TITLE
Cannot insert duplicate key

### ISSUE THREAD

**Issue by denizaydemir** [lukaskubanek/OrderedDictionary#65]
Why can't we insert a key and overwrite if any existing values in the dictionary?

**Comment by denizaydemir** [comment]
I guess there would be an ambiguity about the insertion order of overwritten object.

**Comment by lukaskubanek** [comment]
Exactly. You have to go through two different paths to achieve this.

Check whether the key is already present. If that's the case, update the value. If not, insert the key-value pair at the desired index.
