### ISSUE TITLE
Xcode 13 Build Issues

### ISSUE THREAD

**Issue by willm132** [lukaskubanek/OrderedDictionary#74]
<img width="2449" alt="Screen Shot 2021-09-21 at 8 04 53 AM" src="https://user-images.githubusercontent.com/47162632/134167318-f28ffdfa-720e-428a-918c-3d7dc1b0509c.png">

**Comment by lukaskubanek** [comment]
Hi @willm132, which version of OrderedDictionary are you using? This issue should be fixed as of 4.0.1 AFAIK.

**Comment by willm132** [comment]
I am using SPM

4.0.0 -> Next Major

Issue is fixed with 4.0.1, just needed to manually update the minimum version via SPM.
