### ISSUE TITLE
The Server SSL certificate failed to verify

### ISSUE THREAD

**Issue by crenelle** [lukaskubanek/OrderedDictionary#76]
Using Xcode 14.1 with a project set to target macOS 13.0, Xcode was unable to update Swift Package OrderedDictionary, displaying the error message "The Server SSL certificate failed to verify". This was not a problem when targeting macOS 10.15. It may also be a problem when targeting macOS 12.

Ultimately, Xcode seems to continue attempting to build the whole project without ever succeeding.

**Comment by lukaskubanek** [comment]
Hi Michael, this looks like an issue with your SPM configuration and shouldn’t be specific to this package. You might try fetching a different one to verify that. I’d suggest you to google the error message and look for possible causes.

**Comment by crenelle** [comment]
I was able to recover by backing out changes from the project and deleting the relevant derived data folder for the project. It was very strange in that the build process would lock up after I just removed the derived data folder for the project. The changes I had to remove were made to target macOS 13 instead of macOS 10.15.

Thanks!

Regards,
-Mike

**Comment by lukaskubanek** [comment]
I’m glad you were able to resolve the issue!
